export const ProductData = [
    { id: 1, name: "Product A", sku: "SKU123", price: 50, stock: 20, status: "Active" },
    { id: 2, name: "Product B", sku: "SKU124", price: 70, stock: 15, status: "Inactive" },
    { id: 3, name: "Product C", sku: "SKU125", price: 40, stock: 10, status: "Active" },
    { id: 4, name: "Product D", sku: "SKU126", price: 90, stock: 5, status: "Inactive" },
    { id: 5, name: "Product E", sku: "SKU127", price: 30, stock: 25, status: "Active" },
    { id: 6, name: "Product F", sku: "SKU128", price: 60, stock: 12, status: "Active" },
    { id: 7, name: "Product G", sku: "SKU129", price: 80, stock: 8, status: "Inactive" },
    { id: 8, name: "Product H", sku: "SKU130", price: 100, stock: 3, status: "Active" },
    { id: 9, name: "Product I", sku: "SKU131", price: 55, stock: 18, status: "Inactive" },
    { id: 10, name: "Product J", sku: "SKU132", price: 45, stock: 22, status: "Active" },
    { id: 11, name: "Product K", sku: "SKU133", price: 35, stock: 30, status: "Active" },
    { id: 12, name: "Product L", sku: "SKU134", price: 95, stock: 7, status: "Inactive" },
    { id: 13, name: "Product M", sku: "SKU135", price: 85, stock: 6, status: "Active" },
    { id: 14, name: "Product N", sku: "SKU136", price: 65, stock: 14, status: "Inactive" },
    { id: 15, name: "Product O", sku: "SKU137", price: 75, stock: 11, status: "Active" },
    { id: 16, name: "Product P", sku: "SKU138", price: 20, stock: 40, status: "Active" },
    { id: 17, name: "Product Q", sku: "SKU139", price: 110, stock: 2, status: "Inactive" },
    { id: 18, name: "Product R", sku: "SKU140", price: 125, stock: 1, status: "Active" },
    { id: 19, name: "Product S", sku: "SKU141", price: 55, stock: 21, status: "Inactive" },
    { id: 20, name: "Product T", sku: "SKU142", price: 47, stock: 19, status: "Active" },
    { id: 21, name: "Product U", sku: "SKU143", price: 92, stock: 9, status: "Inactive" },
    { id: 22, name: "Product V", sku: "SKU144", price: 78, stock: 13, status: "Active" },
    { id: 23, name: "Product W", sku: "SKU145", price: 66, stock: 16, status: "Inactive" },
    { id: 24, name: "Product X", sku: "SKU146", price: 33, stock: 28, status: "Active" },
    { id: 25, name: "Product Y", sku: "SKU147", price: 88, stock: 4, status: "Inactive" },
    { id: 26, name: "Product Z", sku: "SKU148", price: 105, stock: 3, status: "Active" }
];
